In [23]:
print("NeoStats Pipeline Started")

NeoStats Pipeline Started

In [24]:
import pandas as pd
import numpy as np

In [25]:
excel_file = "../Data/Raw/retail_data.xlsx"

product_df = pd.read_excel(excel_file, sheet_name="product_details")
retail1_df = pd.read_excel(excel_file, sheet_name="retail_data1")
retail2_df = pd.read_excel(excel_file, sheet_name="retail_data2")

print("All sheets loaded successfully")

All sheets loaded successfully

In [26]:
print(product_df.shape)
print(retail1_df.shape)
print(retail2_df.shape)

(10, 4)
(4243, 16)
(4251, 16)

In [27]:
print(retail1_df.columns)

Index(['transaction_id', 'customer_id', 'customer_name', 'product_id', 'price',
       'product_name', 'category', 'purchase_location', 'city',
       'transaction_date', 'quantity', 'payment_method', 'discount', 'email',
       'phone', 'payment_status'],
      dtype='object')

In [28]:
retail1_df.isnull().sum()

transaction_id         0
customer_id            0
customer_name          0
product_id             0
price                404
product_name           0
category               0
purchase_location      0
city                   0
transaction_date       0
quantity               0
payment_method         0
discount               0
email                  0
phone                  0
payment_status         0
dtype: int64

In [29]:
retail1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4243 entries, 0 to 4242
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     4243 non-null   int64
 1   customer_id        4243 non-null   int64
 2   customer_name      4243 non-null   object
 3   product_id         4243 non-null   int64
 4   price              3839 non-null   float64
 5   product_name       4243 non-null   object
 6   category           4243 non-null   object
 7   purchase_location  4243 non-null   object
 8   city               4243 non-null   object
 9   transaction_date   4243 non-null   object
 10  quantity           4243 non-null   int64
 11  payment_method     4243 non-null   object
 12  discount           4243 non-null   float64
 13  email              4243 non-null   object
 14  phone              4243 non-null   int64
 15  payment_status     4243 non-null   object
dtypes: float64(2), int64(5), object(9)
memory usage: 530.5+ KB

In [30]:
retail_df = pd.concat(
    [retail1_df, retail2_df],
    ignore_index=True
)

print(retail_df.shape)

(8494, 16)

In [31]:
duplicate_count = retail_df.duplicated(
    subset='transaction_id'
).sum()

print("Duplicate Transactions:", duplicate_count)

Duplicate Transactions: 494

In [32]:
retail_df = retail_df.drop_duplicates(
    subset='transaction_id'
)

print(retail_df.shape)

(8000, 16)

In [33]:
retail_df['payment_status'].value_counts()

payment_status
successful    8000
Name: count, dtype: int64

In [34]:
retail_df[retail_df['quantity'] <= 0]

,transaction_id,customer_id,customer_name,product_id,price,product_name,category,purchase_location,city,transaction_date,quantity,payment_method,discount,email,phone,payment_status
33,33,50,Stacey Henderson,104,8000.0,SHOES,CLOTH,online,Mumbai,2025-06-14 00:00:00,-1,Card,0.40,Stacey33@gmail.com,6033182385,successful
75,74,907,Jeffrey Mccall,102,70000.0,PHONE,ELEC,online,Hyderabad,2025-05-26 00:00:00,0,Card,0.40,Jeffrey63@gmail.com,6709574650,successful
77,76,335,Jacob Evans,103,1300.0,shirt,CLOTH,offline,Mumbai,2026-04-11 00:00:00,-2,NetBanking,0.35,JacobEvans@yahoo.com,6483959310,successful
78,77,780,Elizabeth Miller,110,NaN,MICROWAVE,Home Appliances,offline,Delhi,2025-09-14 00:00:00,0,Card,0.30,ElizabethMiller@yahoo.com,8279569798,successful
100,97,723,Christopher Walter,106,80000.0,SOFA,furniture,offline,Hyderabad,2026-02-27 00:00:00,0,NetBanking,0.15,ChristopherWalter@gmail.com,9036645707,successful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8008,7539,1406,Preston Baldwin,101,250000.0,Laptop,ELEC,online,Delhi,2025-12-07 00:00:00,-1,Cash,0.30,Preston57@gmail.com,9482530149,successful
8113,7640,1138,Darren Hall,107,50000.0,Dining table,FURN,offline,Hyderabad,2025-03-09 00:00:00,-1,Card,0.40,DarrenHall@outlook.com,7899737394,successful
8393,7908,1759,Tamara Carter,102,70000.0,PHONE,ELEC,online,Hyderabad,2025-10-30 00:00:00,-2,Cash,0.35,TamaraCarter@outlook.com,6536528655,successful
8432,7944,1353,Tonya Johnson,102,70000.0,Phone,ELEC,online,Delhi,2025-09-15 00:00:00,-2,Card,0.10,Tonya48@gmail.com,9931842216,successful
8440,7951,1554,Darrell Watson,103,1300.0,shirt,Clothing,online,Mumbai,2025-10-27 00:00:00,-2,Cash,0.05,DarrellWatson@gmail.com,9492817032,successful

In [35]:
retail_df = retail_df[
    retail_df['quantity'] > 0
]

print(retail_df.shape)

(7914, 16)

In [36]:
retail_df['transaction_date'] = pd.to_datetime(
    retail_df['transaction_date']
)

print(retail_df['transaction_date'].dtype)

datetime64[ns]

In [37]:
retail_df['year'] = retail_df['transaction_date'].dt.year
retail_df['month'] = retail_df['transaction_date'].dt.month_name()
retail_df['quarter'] = retail_df['transaction_date'].dt.quarter

In [38]:
retail_df = pd.concat([retail1_df, retail2_df], ignore_index=True)

print(retail_df.shape)
print(retail_df['payment_status'].value_counts())

(8494, 16)
payment_status
successful    8000
failed         494
Name: count, dtype: int64

In [39]:
retail_df['payment_status'] = retail_df['payment_status'].astype(str).str.strip().str.lower()

retail_df['payment_status'].value_counts()

payment_status
successful    8000
failed         494
Name: count, dtype: int64

In [40]:
retail_df = pd.concat(
    [retail1_df, retail2_df],
    ignore_index=True
)

print(retail_df.shape)

(8494, 16)

In [41]:
retail_df['payment_status'] = retail_df['payment_status'].astype(str).str.strip().str.lower()

retail_df['payment_status'].value_counts()

payment_status
successful    8000
failed         494
Name: count, dtype: int64

In [42]:
retail_df = retail_df[
    retail_df['payment_status'] == 'successful'
]

print(retail_df.shape)

(8000, 16)

In [43]:
duplicate_count = retail_df.duplicated(
    subset='transaction_id'
).sum()

print("Duplicate transactions:", duplicate_count)

retail_df = retail_df.drop_duplicates(
    subset='transaction_id'
)

print(retail_df.shape)

Duplicate transactions: 0
(8000, 16)

In [44]:
duplicate_count = retail_df.duplicated(
    subset='transaction_id'
).sum()

print("Duplicate Transactions:", duplicate_count)

retail_df = retail_df.drop_duplicates(
    subset='transaction_id'
)

print(retail_df.shape)

Duplicate Transactions: 0
(8000, 16)

In [45]:
retail_df = retail_df[
    retail_df['quantity'] > 0
]

print(retail_df.shape)

(7914, 16)

In [46]:
retail_df['transaction_date'] = pd.to_datetime(
    retail_df['transaction_date'],
    errors='coerce'
)

retail_df['year'] = retail_df['transaction_date'].dt.year
retail_df['month'] = retail_df['transaction_date'].dt.month_name()
retail_df['quarter'] = retail_df['transaction_date'].dt.quarter

In [47]:
product_df.columns

Index(['product_id', 'product_name', 'category', 'price'], dtype='object')

In [48]:
retail_df = retail_df.merge(
    product_df,
    on='product_id',
    how='left',
    suffixes=('', '_master')
)

print(retail_df.shape)

(7914, 22)

In [50]:
retail_df.columns

Index(['transaction_id', 'customer_id', 'customer_name', 'product_id', 'price',
       'product_name', 'category', 'purchase_location', 'city',
       'transaction_date', 'quantity', 'payment_method', 'discount', 'email',
       'phone', 'payment_status', 'year', 'month', 'quarter',
       'product_name_master', 'category_master', 'price_master'],
      dtype='object')

In [51]:
retail_df['price'] = retail_df['price'].fillna(
    retail_df['price_master']
)

In [52]:
retail_df['product_name'] = retail_df['product_name_master']

retail_df['category'] = retail_df['category_master']

In [53]:
def mask_email(email):
    try:
        parts = str(email).split("@")
        return parts[0][:2] + "****@" + parts[1]
    except:
        return email

retail_df['masked_email'] = retail_df['email'].apply(mask_email)

In [54]:
def mask_phone(phone):
    phone = str(phone)
    return "******" + phone[-4:]

retail_df['masked_phone'] = retail_df['phone'].apply(mask_phone)

In [55]:
retail_df['revenue'] = (
    retail_df['quantity']
    * retail_df['price']
    * (1 - retail_df['discount'])
)

In [56]:
revenue_by_category = retail_df.groupby(
    'category'
)['revenue'].sum().reset_index()

revenue_by_category

          category      revenue
0         Clothing   17092535.0
1      Electronics  674462500.0
2        Furniture  243413000.0
3  Home Appliances  229025250.0

In [57]:
revenue_by_city = retail_df.groupby(
    'city'
)['revenue'].sum().reset_index()

revenue_by_city

        city      revenue
0  Bangalore  216720510.0
1    Chennai  246028300.0
2      Delhi  242022530.0
3  Hyderabad  232881480.0
4     Mumbai  226340465.0

In [58]:
monthly_revenue = retail_df.groupby(
    ['year', 'month']
)['revenue'].sum().reset_index()

monthly_revenue

    year      month     revenue
0   2025      April  57418535.0
1   2025     August  99959810.0
2   2025   December  86209270.0
3   2025   February   6064440.0
4   2025    January   9342250.0
5   2025       July  91364460.0
6   2025       June  92879965.0
7   2025      March   7949055.0
8   2025        May  96635265.0
9   2025   November  88707915.0
10  2025    October  96595110.0
11  2025  September  97668850.0
12  2026      April  38130340.0
13  2026     August   4225270.0
14  2026   December   4568125.0
15  2026   February  88949330.0
16  2026    January  86363465.0
17  2026       July   7722595.0
18  2026       June   6293535.0
19  2026      March  83972465.0
20  2026        May   2693300.0
21  2026   November   3382800.0
22  2026    October   4421685.0
23  2026  September   2475450.0

In [59]:
retail_df.to_csv(
    "../Data/Processed/cleaned_retail_sales.csv",
    index=False
)

In [60]:
revenue_by_category.to_csv(
    "../Data/Processed/revenue_by_category.csv",
    index=False
)

revenue_by_city.to_csv(
    "../Data/Processed/revenue_by_city.csv",
    index=False
)

monthly_revenue.to_csv(
    "../Data/Processed/monthly_revenue.csv",
    index=False
)